export const SIGNUP = '/signup';
export const LOGIN = '/login';
// export const PLAYLISTS = '/playlists';
export const CATEGORIES = '/categories';
export const MYSONGS = '/upload';
export const ADMIN = '/admin';
export const RECOVERY = '/recover';
export const ACCOUNT = '/account';
export const FAVOURITES = '/favourites';
export const SEARCH = '/search';
export const DETAILS = '/details';
export const CHANGEPASS = '/changepass';
export const HOME = '/';
export const ALBUM = '/albums';
export const PLAYLIST = '/playlists';
export const ARTIST = '/artists'