export const SIGNUP = '/signup';
export const LOGIN = '/login';
export const CATEGORIES = '/categories';
export const RADIO = '/radio';
export const VIDEO = '/video';
export const ACCOUNT = '/account';
export const FAVOURITES = '/favourites';
export const SEARCH = '/search';
export const DETAILS = '/details';
export const CHANGEPASS ='/changepass';
export const HOME = '/';
export const ALBUM ='/album';
export const PLAYLIST='/playlist';
export const ARTIST='/artist'