

export const TYPES = {
    // Global reducer types
    LOAD_PLAYLISTS: "LOAD_PLAYLISTS",
    LOAD_TRACKS: "LOAD_TRACKS",
    LOAD_USERS: "LOAD_USERS",
    LOAD_ALBUMS: "LOAD_ALBUMS",
    LOAD_ARTISTS: "LOAD_ARTISTS",
    LOAD_GENRES: "LOAD_GENRES"
}