export const TYPES = {
  // Global reducer types
  LOAD_PLAYLISTS: "LOAD_PLAYLISTS",
  LOAD_TRACKS: "LOAD_TRACKS",
  LOAD_USERS: "LOAD_USERS",
  LOAD_ALBUMS: "LOAD_ALBUMS",
  LOAD_ARTISTS: "LOAD_ARTISTS",
  LOAD_GENRES: "LOAD_GENRES",

  // Auth reducer types
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_UNSUCCESS: "LOGIN_UNSUCCESS",
  LOGOUT: "LOGOUT",
  RESET_ERROR: "RESET_ERROR",
  SET_FIRST_TIME_FALSE: "SET_FIRST_TIME_FALSE",
  REFRESH_PAGE: "REFRESH_PAGE",

  //Player reducer types
  ADD_SONG: "ADD_SONG",
  PLAY_SONG: "PLAY_SONG",
  ADD_TRACKS_TO_LIST: "ADD_TRACKS_TO_LIST",
  ADD_TRACKS_TO_QUEUE: "ADD_TRACKS_TO_QUEUE",

  // Recovery reducer types
  SET_USER_ID: "SET_USER_ID",
  SET_TOKEN: "SET_TOKEN",

  // User reducer types
  SET_LISTS: "SET_LISTS",
  SET_FAVOURITES: "SET_FAVOURITES",
  SET_USER_PLAYLIST: "SET_USER_PLAYLIST",
  DELETE_FAVOURITES: "DELETE_FAVOURITES",
  SET_MY_TRACKS: "SET_MY_TRACKS",
};

export const LANGUAGES = {
  SPA: "es",
  ENG: "en",
  CHN: "chn",
  FRA: "fr"
}

