export { default as App } from './App';

export { default as AccountSettings } from './components/AccountSettings/AccountSettings';
export * from './components/Categories/Categories';
export { default as Song } from './components/Categories/Song';
export * from './components/Categories/SongCard';
export * from './components/Favourites/Favourites';
export { default as Category } from './components/Home/Category';
export { default as Chart } from './components/Home/Chart';
export { default as Cover } from './components/Home/Cover';
export { default as Section } from './components/Home/Section';
export * from './components/NavBar/NavBar';
export * from './components/Radio/Radio';
export { default as Error } from './components/Register/Error';
export { default as RecoverModal } from './components/Register/RecoverModal';
export * from './components/Video/Video';
export * from './main';

export { default as AccountSettingsPage } from './pages/AccountSettingsPage';
export * from './pages/CategoriesPage';
export { default as FavouritesPage } from './pages/FavouritesPage';
export * from './pages/HomePage';
export * from './pages/Layout';
export { default as Login } from './pages/Login';
export * from './pages/RadioPage';
export { default as Register } from './pages/Register';
export { default as Search } from './pages/Search';
export * from './pages/VideoPage';
export * from './router/MyRouter';
export { default as PrivateRoute } from './router/PrivateRoute';
export * from './router/paths';
