name: Release
on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
  
    permissions: 
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.0

      - name: Install dependencies
        run: npm i
        env:
          CI: true
        
      - name: Configure Git User
        run: | 
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Get package version
        run: |
          NEXT_RELEASE=$(jq '.version' package.json | sed 's/-SNAPSHOT.0//' | xargs npm version --no-git-tag-version | sed 's/v//')
          echo "NEXT_RELEASE=$NEXT_RELEASE" >> $GITHUB_ENV
        shell: bash

      - name: Create env
        run: |
          touch .env.production
          echo VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }} >> .env
          echo VITE_BACKEND=${{ secrets.VITE_BACKEND }} >> .env
          cat .env


      - name: Build Production
        run: npm run build:prod

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'smoothsick-front-*.zip'
          generateReleaseNotes: true
          tag: ${{ env.NEXT_RELEASE }}
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Create SNAPSHOT
        run: npm version prerelease --preid SNAPSHOT --no-git-tag-version

      - name: Update version in remote
        run: |
          git add package.json
          git add package-lock.json
          git commit -m "chore: prepare snapshot"
          git push

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & push
        uses: docker/build-push-action@v3
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/smoothsick-front:${{ env.NEXT_RELEASE }}

#   - name: Deploy
#     run: |
#       git config --global user.name devs-toni
#       git config --global user.email devs.toni@gmail.com
#       git remote set-url origin https://${github_token}@github.com/${repository}
#       npm run deploy
#     env:
#       user_name: 'github-actions[bot]'
#       user_email: 'github-actions[bot]@users.noreply.github.com'
#       github_token: $#{{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
#       repository: $#{{ github.repository }}
